const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('dist/index.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);const els=Object.fromEntries(ids.map(id=>[id,{value:'',checked:false,style:{},textContent:'',innerHTML:'',disabled:false}]));
Object.assign(els.object,{value:'robot'});Object.assign(els.target,{value:'r1'});els.frame.value='world';els.semantic.value='restaurant';els.qx.value=els.qy.value='1';
const registry=[];const ctx={document:{getElementById:id=>{assert(els[id],id);return els[id]},modelContext:{registerTool:t=>registry.push(t)}},window:{},setInterval:()=>1,clearInterval:()=>{},MouseEvent:function(){}};
vm.runInNewContext(script,ctx);const sim=ctx.window.citySimulation;let prev=sim.snapshot(),charging=0;
for(let i=0;i<5000;i++){sim.step();const now=sim.snapshot();assert(sim.world[now.y][now.x]==='road','robot entered building');assert(Math.abs(now.x-prev.x)+Math.abs(now.y-prev.y)<=1,'nonadjacent move');assert(now.energy>=0&&now.energy<=100);if(now.energy>prev.energy)charging++;prev=now;if(now.state==='Complete')break;}
assert(prev.order===3,'orders incomplete');assert(prev.state==='Complete','exploration incomplete');assert(charging>0,'charging never happened');assert(prev.known.length===32*38,'map not fully explored');
const steps=registry.find(t=>t.name==='step_delivery_simulation');assert(steps);assert.throws(()=>steps.execute({steps:101}));sim.reset();const initial=sim.snapshot();steps.execute({steps:2});assert(sim.snapshot().tick===2);sim.reset();assert(sim.snapshot().x===16&&sim.snapshot().energy===60);els.qx.value='32';els.locate.onclick();assert(els.locationResult.textContent.includes('Enter whole numbers'));console.log(JSON.stringify({completedAt:prev.tick,orders:prev.order,knownCells:prev.known.length,chargingSteps:charging,reset:'passed',invalidCoordinates:'passed',toolValidation:'mock context passed',initialKnown:initial.known.length}));
